- README.md
MongoDB University 웨비나
주최 : MongoDB University Korea
일시 : 02. 25(목) 14:00 ~ 15:00
내용
- MongoDB University 소개
- 샘플 예제 60문제 풀이
- 스터디 가이드
혜택
- 기간: ​~2021년 3월말까지
- 혜택(1):​ 기간 내에 시험을 응시하신 모든분들께 ​‘응시료 50% 할인​’
- 혜택(2)​: 기간 내에 시험을 응시&합격하신 모든분들께 ‘​응시료 100% 반환’+ 몽고디비 기프트박스​’
> docs : MongoDB University 웨비나 추가

- README.md
CNCF에서 주최하는 컨퍼런스 KubeCon을 추가했습니다.
> KubeCon 온라인 컨퍼런스 추가

- README.md
- __[2021 오픈소스 컨트리뷰션 아카데미](https://www.oss.kr/contribution_academy)__
- 분류: `오픈소스`
- 주최: 과학기술정보통신부
- 신청: 07. 05(월) ~ 07. 26(월)
부분을 추가했습니다 이번엔 실수 없길 ㅠㅠ
> 추가: 2021오픈소스 컨트리뷰션 아카데미

- README.md
개발자 동아리에 CEOS를 추가했습니다.
CEOS는 신촌지역기반 연합 IT 창업 동아리입니다.
> 개발자 동아리: CEOS 추가

- README.md
[GitHub 2021 Secure Coding] 와 [소프트웨어를 통한 제조 기업 생산성 높이기 | 메가존클라우드 X AWS] 의 링크가 바뀌어 있어 수정했습니다!
> Fix : 바뀐 행사 링크 수정

- README.md
> fix: 스프린트 서울 url 오류 수정

- README.md
22년 1월의 섹션을 추가했습니다. 형식이 잘 맞는지 모르겠네요 🥲
패스트캠퍼스의 sudo : CTO’s Tech Talk 2022행사를 추가했습니다.
> sudo : CTO’s Tech Talk 2022 행사 추가

- README.md
개발자 동아리 Mash-Up 부분에서 표시되는 링크와 실제 리다이렉트 되는 링크가 다른 점을 수정하였습니다.
`mash-up.it` -> `mash-up.kr`
> 주소 표기 다른점 수정

- README.md
DACrew 3기 모집 주소 링크가 https://festa.io/events/2367로 잘못 지정되어 있어서 아래의 주소로 변경하였습니다. 
https://dacon.notion.site/DACrew-3-17d5c216544f4145b58a60fd1f42a217
> DACrew 3기 모집 주소 변경

- README.md
- AUSG의 노션 링크(4기 지원 기간 이후 변경사항 없는 것으로 보임)를 현재 운영 중인 [웹사이트](https://ausg.me/)로 변경
- 현재 운영되지 않는 동아리를 동아리 목록에서 제거
- 1097f41 docs: AUSG 링크 현재 운영중인 홈페이지 링크로 변경
- ee862f5 docs: 운영되지 않는 동아리 목록에서 제거
---
관심있게 지켜보다 첫 PR보냅니다😆
> docs: 개발자 동아리 항목 변경사항 적용

- README.md
- **소주콘 Shot 1 : 진로 빨간 뚜껑** 행사의 일시 변경
> docs:`소주콘 Shot 1 : 진로 빨간 뚜껑` 행사일시 변경

- README.md
- [2022 오픈소스SW 라이선스 전문교육 일반과정 1차](https://www.olis.or.kr/consulting/openswStudyDetail.do?seq=442)와 링크가 동일하여 `고급과정` 신청 링크에 맞게 수정했습니다.
---
항상 좋은 정보 공유해주셔서 감사합니다.
> update : 오픈소스SW 라이선스 전문교육 고급과정 2차 링크 수정

- README.md
> docs, fix: HashiCorp 창업자와 함께하는 HashiCorp Strategy Day 2023

- README.md
마이크로소프트에서 진행하는 Build 컨퍼런스가 빠져 있어서 추가했습니다.
> Microsoft Build 2023 추가

- README.md
구글 해시 코드는 2023년을 끝으로 더 이상 열리지 않습니다.
* https://codingcompetitions.withgoogle.com/hashcode/
> Remove Google Hash Code

- README.md
Angel Hack Seoul 은 더이상 개최하지 않는지 url 접속이 불가합니다.
스프링 캠프는 url이 변경되어 2023 버전 url로 최신화 했습니다.
> Angel Hack Seoul 링크 삭제, 스프링 캠프 url 최신화

- README.md
안녕하세요, **[가짜연구소(7th Pseudo Lab) 리서치팀](https://pseudo-lab.com/HuggingFace-KREW-26245cf06e5240d09973d8b4b4027a69)에서 활동 중인 [Hugging Face KREW Hackathon 2023](https://pseudo-lab.github.io/huggingface-hackathon23/ko/)** 운영진입니다 😄 
**Hugging Face KREW Hackathon 2023 행사를 Dev-Event에 추가 가능**한지 확인 부탁드리고자 PR를 남겼습니다.
국내 Hugging Face 커뮤니티 활성화 및 네트워킹을 목적으로 11월 10일까지 온라인 해커톤을 진행되며,  
[오프라인 세션](https://event-us.kr/huggingfacekrew/event/72612)은 11월 11일 [7th PseudoCon 행사]( https://event-us.kr/pseudolab/event/73265)에서 예정되어 있습니다.
해당 행사가 Dev-Event에 추가되어도 괜찮으신지 확인 부탁드립니다. 감사합니다.
> docs: add Hugging Face KREW Hackathon 2023

- README.md
행사 참가 등록 링크가 잘못 들어가 있어 수정 하였습니다.
> UbuCon Asia 2023 & Ubuntu Summit 2023 Recap Seminar 잘못된 URL 수정

- README.md
개발 교육에 'Apple Developer Academy @ POSTECH'를 추가했습니다.
> docs: add Apple Developer Academy 개발 교육

- README.md
스파르타코딩클럽과 크래프톤 정글이 공동 주최하는 대학생 IT 공모전을 추가했습니다.
> add: All-in 코딩 공모전 - 대학 생활 개선 편

- README.md
Tensorflow KR가 4월 1일 이후로 AGI KR로 변경되어 PR하였습니다.
> Rename dev group(Tensorflor KR->AGI KR)

- README.md
- SOPT 도메인 변경 
- 페이스북 링크 삭제 요청 (사유: 페이스북 플랫폼 사용 하지 않음)
> SOPT 도메인 변경

- README.md
- 기존 엘리스 링크 접속 시 500 에러가 발생합니다.
- 올바른 엘리스 링크로 수정하였습니다.
> docs: 엘리스 도메인 변경

- README.md
안녕하세요!
4월 26일(토)에 GDG Campus Korea Chapter에서 행사가 진행되어 행사랑 저희 Chapter 링크 추가했습니다!
추가로 개발 교육 기관 목록에 '카카오테크 부트캠프'를 추가했습니다.
> add Build with AI: GDG StartUP Lab 행사 및 campus korea chapter

- README.md
안녕하세요, DND 해커톤 일정이 있어 공유드립니다 🥸
- __[DND 해커톤 :: 퍼즐처럼 맞춰가는 1박 2일의 즐거움!](https://event-us.kr/dndacademy/event/101920?utm_source=eventus&utm_medium=organic&utm_campaign=search-result)__
- 분류: `오프라인(서울 마포구)`, `유료`, `해커톤`
- 주최: DND
- 접수: 04. 23(수) ~ 05. 11(일)
> docs: 2025 dnd 해커톤 추가
