README.md
좋은 레포를 알게 되어, 가능하다면 저희 동아리 설명도 넣고 싶습니다.
추가로, footer 이미지가 잘 작동하지 않는 듯 하여 비슷하게 중앙정렬을 구현해 보았습니다
=> 개발자 동아리 AUSG 추가 및 푸터 이미지 중앙정렬

README.md
좋은 저장소 만들어주셔서 감사합니다!! 자주 확인하며, 너무나 잘 사용하고 있습니다 :)
모두의 연구소 URL이 잘못된 것 같아서 수정 후, PR 요청드립니다.
감사합니다!!!😀
그리고 Actions와 Issue의 Watch사용 시 mail을 보내주는 시스템을 이용해서 Mail로 주기적으로 행사를 보내주는 것을 한번 만들어서 자동화(?)시켜보고 싶습니다!
혹시 방향성을 괜찮게 생각하신다면 리플 부탁드립니다😄
=> docs : 모두의 연구소 url 수정

README.md
=> 우아한테크 세미나 추가

README.md
=> 리드미, 개발자 동아리 부문에 SOPT, 멋쟁이사자처럼, DSC Korea 추가

README.md
우아한 테크 세미나 추가
https://docs.google.com/forms/d/e/1FAIpQLSfxTaez84JSLgfiTeUs6yddX_LHEaV0zQ1zz7yoDgNikDnZpA/viewform
=> docs : 우아한 ATDD 행사 추가

README.md
항상 감사합니다.
m1 쓰시는 많은 분들께 희소식인 행사인 것 같아서 서둘러 올려봅니다.
=> [추가] dockercon 행사추가

README.md
새로 추가된 행사에 대하여 강조표시를 추가했습니다.
추가적으로 행사 날짜의 포멧을 통일했습니다.
=> fix : format 수정

README.md
운영해주셔서 항상 감사합니다 ^.^
네이버 검색 콜로키움 행사 추가합니다....!!
=> [추가] 네이버 search colloquium Global Re:Search 행사 추가

README.md
=> 배리어프리 앱 개발 공모전 행사 추가

README.md
- 우아한테크러닝 4기 : 나만의 노션 만들기 (feat.시니어봇) 추가
- 해당 내용은 이메일로 발송와서 Google Docs Form 링크를 첨부합니다.
=> [Update] 우아한테크러닝 4기 추가합니다.

README.md
=> Add '우아한 테크 러닝'

README.md
구독 서비스 운영 중 발견한 중복행사 삭제 및 facebook 컨퍼런스 추가합니다.
=> 행사 추가 및 중복 행사 삭제

README.md
Facebook 그룹 MLOps KR에서 진행하는 행사 추가합니다.
=> [Update] 제1회 MLOps KR community event 추가합니다.

README.md
Graphics hardware와 Interactive Ray-tracing에 관한 좋은 웨비나가 있어서 공유합니다 :)
=> 추가 : HPG 온라인 웨비나

README.md
=> YAPP 19기 모집 추가

README.md
=> HackaLearn 2021 행사 추가

README.md
=> 두굿 해커톤 행사 추가

README.md
이전 Commit (338385951fca3a84ecbeb38cfc002f43c598ada4)이 반영되면서 링크가 잘 못 들어간 행사가 있어서 개선했습니다 :)
=> Fix : 잘못된 행사 링크 개선

README.md
- 모여서 각자 글쓰기 행사를 추가했습니다.
- 이전에 업데이트 했던 코프링 행사의 접수를 일시로 바꾸었습니다.
=> Update : 모여셔 각자 글쓰기 행사 추가

README.md
매년 열리고 있는 JunctionX Seoul 해커톤 링크를 추가했습니다.
=> update: JunctionX Seoul 추가

README.md
- Add Line developer day 2021
- https://linedevday.linecorp.com/2021/ko/
=> [Add] Line developer day 2021

README.md
11월 행사 중 KT AIVLE School 링크가 잘못되어 변경 요청드립니다.
=> KT AIVLE School 링크 변경

README.md
팀 프로젝트 완성, 고도화를 위한 팀 부스팅 프로그램 UPF를 추가합니다.
직접 운영하고 있는 프로그램이니 혹시 궁금한 점이 있으시면 질문 주세요 😁
- Notion: https://www.unit.center/upf
- facebook: https://www.facebook.com/unit.center
=> UPF 동아리 추가

README.md
=> sw 마에스트로 모집 공고 추가했습니다.

README.md
- 1월 우아한테크세미나: 시각적 요소 테스트 자동화하기
- https://docs.google.com/forms/d/e/1FAIpQLSfi1KvMtw_TpCWjDmkbQWfoSuHHm2yTQB8BxAIoTrnZjCJPDQ/viewform
=> [Add] 1월 우아한테크세미나 추가

README.md
- AWS Innovate – AI/ML 특집 행사 추가했습니다!
- https://aws.amazon.com/ko/events/aws-innovate/machine-learning/?refid=em_setpw_kr_innovate_aiml22q1&trkcampaign=innovate-ml
=> [ADD] AWS Innovate – AI/ML 특집 행사 추가

README.md
쭉 보다보니... Ubuntu Korea 는 보이지 않아서 추가 해 보았습니다 :)
=> 모임 목록에 우분투 한국 커뮤니티 추가

README.md
개발자 모임 카테고리에 새로운 항목을 추가하여 커밋합니다 😉
=> [ADD] 개발자 모임 카테고리 항목 추가

README.md
- 제4회 오픈 인프라 개발 경진 대회 (OIDC 2022) 추가했습니다!
- http://www.oidc.co.kr
=> [ADD] 제4회 오픈 인프라 개발 경진 대회 추가

README.md
- https://resources.github.com/webcasts/kr-DevOps-Security/
- DevOps 행사와 Security 행사가 나눠서 진행되서 요일만 나눠서 추가했습니다.
- 등록한 메일로 웨비나 링크가 발송됩니다.
=> [ADD] GitHub Learning Journey: DevOps & Security 행사 추가

README.md
Mash-Up 12기 모집 추가했습니다.
https://mash-up.kr/
=> Mash-Up 12기 모집 추가

README.md
- Add 우아한테크캠프 Pro 4기
- https://edu.nextstep.camp/c/lqsBs7x0
=> [Add] 우아한테크캠프 Pro 4기 추가

README.md
- Node.js Korea
- https://www.facebook.com/groups/nodejskr
=> [ADD] Node.js Korea 추가

README.md
- 7월 2일에 진행하는 디프만 관련 행사 시간이 잘못되어 수정하였습니다.
- 디프만에 대한 소개글을 변경하였습니다.
=> Fix: 디프만 최종발표회 시간 변경 및 디프만 정보 변경

README.md
- 개발자 모임에 GraphQL Korea를 추가했어요.
=> feat: add GraphQL Korea in main README.md

README.md
=> Update Tensorflow KR

README.md
htthttps://events.dell.com/event/8721d365-6b70-46e5-aa0c-240d89e01ea2/summary
https://events.dell.com/event/8721d365-6b70-46e5-aa0c-240d89e01ea2/summary
=> DELL Technologies Forum 링크 수정

README.md
개발자 교육에
- 크래프톤 정글
- 네이버 부스트캠프
- 42 SEOUL
추가하였습니다.
감사합니다.
=> 개발자 교육 영역 업데이트했습니다.

README.md
- 2022 우리 코딩 페스티벌을 추가했습니다.
- https://www.ybmit.com/event/revent/woori_Code/event.jsp
=> docs: 우리은행 코딩 페스티벌 추가

README.md
- 우리 코딩 페스티벌 줄바꿈 수정
- 주회 수정: 우리은행 -> 우리 FIS, YBM
=> docs: 우리 코딩 페스티벌 줄바꿈 수정 및 주최 수정

README.md
모집에 적힌 날짜가 일시더라구요. 헷갈리길래 일시로 수정했습니다.
=> docs: UNITHON 모집일 수정

README.md
한국 Microsoft 오프라인 행사 일정을 추가했습니다
=> docs: add Microsoft Ignite Spotlight on Korea

README.md
기존 URL 이 잘못되어 접근 가능한 URL 로 변경했습니다.
https://festa.io/events/3057 -> https://festa.io/events/3064
=> AWS & LG CNS’s Pick! ’23년 AWS 핵심 서비스 4가지 URL 변경

README.md
DEVOCEAN 2월 테크 세미나 - "성능 테스트와 K6 도구 소개" 추가합니다!
=> DEVOCEAN 2월 테크 세미나 추가

README.md
행사 : AWSKRUG 구로디지털 #gudi 소모임
링크 : https://www.meetup.com/ko-KR/awskrug/events/291284183/
=> [ADD] AWSKRUG 구로디지털 #gudi 소모임 추가

README.md
XR, web3.0, 모션캡쳐, virtual human 등의 프로젝트를 해온 서울대학교 기반 메타버스 학회 XREAL 4기 리크루팅 정보입니다!
=> docs: add XREAL 4기 리크루팅

README.md
XREAL 메타버스 학회에 대해서 적어보았습니다. 메타버스에 대한 비전을 XREAL 에서 실현해보세요!
=> docs: XREAL 메타버스 학회 소개

README.md
Design Challenge (Asia Pacific) - Part 2 추가합니다.
=> [ADD] Design Challenge (Asia Pacific) - Part 2 추가

README.md
- 카카오 테크 캠퍼스
- https://www.kakaotechcampus.com/user/index.do
=> docs: 개발 교육 카카오 테크 캠퍼스 추가

README.md
=> 개발 교육 메타버스 아카데미 추가

README.md
공식 페이지(https://toss.im/career/toss-study-club) 정보입니다.
=> Fix: 토스 스터디 클럽 모집 기간 수정

README.md
접수 기간을 수정하는 과정에 들어간 공백을 제거했습니다.
앞으로 더 신경쓰도록 하겠습니다.
=> Fix: 토스 스터디 클럽 공백 제거

README.md
=> [ADD] 6th PseudoCon 2023 

README.md
새싹톤 기존 9일에서 마감일이 14일로 연기되었습니다.
=> 새싹톤 14일까지로 연기되었습니다.

README.md
OpenInfra Community Days Korea 2023 행사 추가합니다!
=> OpenInfra Community Days Korea 2023 행사 추가

README.md
데브이벤트 추가하다가 오타가 있길래,, Next -> Nest로 변경했어~!!
=> 리드미 오탈자 수정

README.md
‘대한민국 인공지능 위크 AI for Korea 2023’ 추가합니다.
=> Add AI for Korea 2023

README.md
Seoul MLOps Community 행사 추가합니다!
=> Seoul MLOps Community 추가

README.md
=> AI Summit Seoul 행사 추가

README.md
Feature Store Summit 2023 추가합니다~
=> Feature Store Summit 2023 행사 추가

README.md
프로젝트 기반의 부트캠프 교육 커널360 입니다.
홈페이지 : https://kernel360.co.kr/
소개 : https://kernel360.co.kr/program
=> [ADD] Kernel360

README.md
- 없어진 도메인 및 접속 불가 링크 삭제
- 중복 링크 제거
=> fix/dev-meet-link 개발자 모임 링크 수정

README.md
Best of Data+AI Summit 2023 컨퍼런스 추가합니다~
=> Best of Data+AI Summit 2023 컨퍼런스 추가

README.md
대관문제로 인해 날짜가 10월 21에서 10월 14일로 변경 되어 수정 한 내용 PR 올렸습니다.
=> docs: 데이터야놀자 2023 날짜 수정

README.md
I/O Extended 2023 Incheon 추가합니다.
=> I/O Extended 2023 Incheon 추가

README.md
Flutter MeetUp - In Songdo 이벤트 등록합니다.
https://festa.io/events/3887
=> Add: Flutter MeetUp - In Songdo 이벤트 추가

README.md
=> Fix: 웹3 해커톤 링크 수정 #396

README.md
=> Add: 개발자모임 정보 (GDG Incheon & Songdo with Flutter Songdo)

README.md
서울대학교 기반 XR 중심 메타버스 학회 XREAL 5기 리크루팅 정보입니다!
=> docs: add XREAL 5기 리크루팅

README.md
=> 데보션 테크데이 행사 추가

README.md
HMG Developer Conference 추가합니다~
=> HMG Developer Conference 추가

README.md
Netlify Compose 2023이 빠져 있어서 추가했습니다.
=> Netlify Compose 2023 추가

README.md
정기적으로 열리는 개발자 행사인 파이콘 한국 / PyCon Korea 를 목록에 추가합니다.
=> 파이콘 한국, 정기적 개최 행사 목록에 추가

README.md
=> 교육관련 앱/웹 서비스 제작 주니어 해커톤 내용 수정

README.md
대학별 IT연합 개발자 동아리 구름톤 유니브를 추가했습니다.
=> docs: add goormthon univ 개발자 동아리

README.md
안녕하세요~!🙇‍♂️ 오랜만에 PR올려요~!
DND 동아리에서 운영진으로 활동하고 있고, 10기 모집이 오늘부터 시작이라 추가하였습니다~!
- https://www.dnd.ac/
- 모집: 11. 20(월) ~ 12. 18(월)
- 개발자 동아리 > D&D 에서 DND로 변경하였습니다.
=> docs: DND 10기 모집 추가

README.md
AI Link 모임 및 제1회 Meetup 'Link Up' 등록합니다.
=> Add: AI Link 모임 및 제1회 Meetup 'Link Up' 등록

README.md
**개발 교육**에 "삼성 청년 SW 아카데미(SSAFY)"를 추가했습니다.
=> docs: add SSAFY 개발 교육

README.md
1월 행사 일정에 2024 Mobility SW HACKATHON 를 추가하였습니다.
=> docs: add 2024 Mobility SW HACKATHON

README.md
- 걸스인텍 코리아 영문 표기 수정 (대문자 -> 소문자 i)
- 걸스인텍 코리아 유튜브 추가
- 개발자 모임에 걸스인텍 버클업 추가
감사합니다 :)
=> docs: 걸스인텍 관련 내용 수정 및 개발자 모임 추가

README.md
k를 소문자 -> 대문자로 변경했습니다.
감사합니다 :)
=> fix: 고랭코리아 영문 표기 수정

README.md
- 개발자 모임에 **AsyncSwift**를 추가했습니다. 
- 정규적으로 열리는 개발자 모임에 **SyncSwift**를 추가했습니다.
=> docs: AsyncSwift, SyncSwift 추가

README.md
안녕하세요!
AWS Cloud Club in South Korea에서 주최하는 Student Community Day 행사 정보 추가했습니다.
=> 2024 AWS Cloud Club Student Community Day (ACCSCD) 행사 정보 추가했습니다

README.md
개발 동아리에 BOAZ를 추가했습니다.
데이터분석뿐만 아니라 하둡,스파크, 카프카와 같은 데이터 엔지니어링도 수행하기에 개발동아리 알맞는 것 같아서 PR 올립니다.
=> BOAZ 동아리 추가

README.md
=> 개발 교육기관 추가

README.md
개발자 모임에 'C++ Korea'  추가 요청드립니다.
=> Add: C++ Korea 개발자 모임 추가

README.md
- [원티드X네이버클라우드] 생성형 AI 시대 직장인을 위한 프롬프톤 추가
- 2024 스마일게이트 AI 서비스 위클리톤 추가
=> 원티드 프롬프톤, 스마일게이트 위클리톤 추가

README.md
2024 C++ Korea Meet-up 일정 추가했습니다!!
=> 2024 C++ Korea Meet-up 일정 추가

README.md
안녕하세요.
AUSG 8기 오거나이저 송승호입니다.
곧 열릴 AUSGCON 2024 행사를 위한 발표자 모집 폼을 추가했습니다.
감사합니다 :)
=> AUSGCON 2024:try-catch 발표자 모집 추가

README.md
마크다운 문법 때문에, <Flutter> 영역이 표시되지 않고있어, 이스케이프 문자를 추가하였습니다!
=> Future<Flutter> 에 이스케이프 문자를 추가합니다.

README.md
Facebook 링크가 아님에도, Facebook 텍스트에 링크가 걸려있어 수정하였습니다.
=> docs: Change link text from [facebook] to [homepage] as it is not a Facebook link

README.md
안녕하세요! 오랜만에 인사드립니다!
9월 8일부터 SIPE 3기 모집을 시작해서 일정추가합니다!
SIPE 운영진 활동을 하고 있어서 소개글도 수정했습니다!
항상 감사합니다~
=> docs: sipe 3기 모집 일정 추가 및 sipe 소개 내용 업데이트

README.md
=> feat: update GopherCon Korea schedule

README.md
안녕하세요! 
테오콘2024 행사 일정이 확정되어 추가 PR올립니다. 🙇
=> docs : add Teoconf2024

README.md
=> 개발 교육 기관 추가

README.md
https://cloudclub.oopy.io/ -> https://www.cloudclub.kr/
=> Cloud Club 공식 홈페이지 url 수정

README.md
9oormthon Univ → 9oormthonUNIV으로 오타 수정하였습니다!
=> docs : 오타 수정

README.md
안녕하세요.
개발 교육 탭에 KT AIVLE School을 추가했습니다!
=> Add KT AIVLE School

README.md
안녕하세요, SIPE입니다!
25년 3월 11일부터 25년 3월 23일까지 SIPE 4기 모집을 받고 있어, 일정 추가하였습니다!
감사합니다!
=> docs: sipe 4기 모집 일정 추가 및 sipe 소개 내용 업데이트

README.md
안녕하세요!
1. 대학교 연합 앱 런칭 동아리 UMC의 URL이 다음과 같이 변경되어 수정했습니다.
기존: [https://makeus.in/umc/](https://makeus.in/umc/)
변경: [https://umc.makeus.in/](https://umc.makeus.in/)
2. 개발 교육 기관 목록에 '프로그래머스 데브코스'를 추가했습니다.
=> docs:  url 변경, 개발 교육 기관 추가

README.md
AWS Korea와 함께하는 코드트리 코딩 기초 챌린지 참여자를 모집하게 되었습니다!
무료로 진행되며, 동기부여를 위해 다양한 보상을 준비해뒀습니다.
=> docs: AWS Korea와 함께하는 코딩 기초 챌린지 참여자를 모집합니다.

README.md
1. 자료구조, 알고리즘 교육 사이트 코드트리를 교육 테이블에 추가합니다.
2. 코드트리에서 운영하고 있는 글로벌 알고리즘 커뮤니티를 개발자 모임에 추가합니다.
감사합니다!
=> docs: 코드트리 사이트 및 커뮤니티 등록

README.md
안녕하세요 
2025년 5월 17일(토) 에 진행되는 개발자 행사 
Build With AI for Everyone 행사 정보를 추가했습니다.
=> 25년 5월 Build With AI for Everyone 행사 등록

README.md
안녕하세요, @gdsc-konkuk 입니다
25년 5월 24일에 열리는 개발 행사 일정 추가했습니다
[![89e968ed1baa4d9d989450817f6e9693](https://github.com/user-attachments/assets/670a194f-4c9c-4b49-8c3f-a24f34a3a557)](https://event-us.kr/gdgockonkuk/event/103357)
감사합니다!
=> Docs: 5월 Kprintf 2025 행사 등록

README.md
- 타입스크립트 백엔드 밋업 (TSBM)을 6월 28일 토요일, 역삼 센터필드에서 개최합니다! (AWS)
- 지난 4월 1회에 이어 2회를 개최하게 되어서 PR날립니다!
감사합니다 :)
=> docs: typescript backend meetup (June)

README.md
=> 구름톤 14기 모집 일정 추가

README.md
안녕하세요. 
AUSG 퍼블릭 빅챗 행사와 9기 신규 부원 모집 추가했습니다!
감사합니다.
=> docs : add AUSG 9th events

README.md
안녕하세요 
10월 컨퍼런스 Flutter Alliance 2025
11월 컨퍼런스 GopherCon Korea 2025
정보를 추가했습니다. 
감사합니다.
=> 10월, 11월 컨퍼런스 추가 (Flutter Alliance 2025, GopherCon Korea 2025) 
